### PR TITLE
Allow Administrate 0.15

### PR DESCRIPTION
**Pull request by ja**

### CODE REVIEW

**Comment by pedantic-git** [comment]
Hi @ja - I'm assuming you've tested this and it works OK out of the box?

**Comment by ja** [comment]
Hi @pedantic-git, yes, tested and it's working perfectly.

**Comment by pedantic-git** [comment]
Cool! I will merge this and release a new version probably on Friday

**Comment by pedantic-git** [comment]
Hi @ja - that's released as https://rubygems.org/gems/administrate-field-lat_lng/versions/1.13.0 - thanks for the patch!

**Pull request merged**
