### PR TITLE
Add location search

### PR DESCRIPTION
**Pull request by klaseskilson**
Hey again,

Here's a PR that adds a search box using Google Places API search. This allows the user to find locations without having to pan and zoom. It uses [Twista/leaflet-google-places-autocomplete](https://github.com/Twista/leaflet-google-places-autocomplete).

Hit me with your feedback! 👍

### CODE REVIEW

**Comment by pedantic-git** [comment]
Hey! This is a cool feature. When I try it, I can search for places but when I select one the map re-centres on it without updating the pin or the lat/lng values themselves. Is it possible to make that happen because I think it's a little confusing without it.

**Comment by klaseskilson** [comment]
Good idea! Will update PR.

**Comment by klaseskilson** [comment]
@pedantic-git Good to go. Thoughts?

**Comment by pedantic-git** [comment]
This is awesome! Let me merge and release.

**Comment by pedantic-git** [comment]
And released as 1.2.0.

**Pull request merged**
